on: [push]
jobs:
  build-finishes-quickly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "`cargo build` finishes quickly on first run and after a change."
        run: |
          make_sure_build_finishes_in() {
            start_time=$(date +%s)

            cargo build
            end_time=$(date +%s)
            maximum_seconds_to_build=$1
            seconds_elapsed=$((end_time - start_time))
            if [ "$seconds_elapsed" -gt "$maximum_seconds_to_build" ]; then
              echo "Build took too long: $seconds_elapsed s"
              exit 1
            fi
          }

          make_sure_build_finishes_in 10

          echo "fn _f() { println!(\"Rebuilds should be quick.\"); }" >> src/main.rs
          make_sure_build_finishes_in 1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --all-targets -- --deny warnings

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo run

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --all-targets
